version: "3.9"

services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    networks:
      - mern_network
    environment:
      GEMINI_API_KEY: AIzaSyAjLTI4QqUHI8xQxo1pZR9oUi4fuc4nBVk
      MONGO_URL: mongodb+srv://CookWell:12345@cookwell.mj3qnad.mongodb.net/?retryWrites=true&w=majority&appName=CookWell
      JWT_SECRET: secrete
      EMAIL_USER: mrunknown.2005.2027@gmail.com
      EMAIL_PASS: mxscayqtduvwwoce
      
    volumes:
      - ./Backend:/app
      - /app/node_modules   # Prevent overwriting node_modules inside container
    restart: unless-stopped

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    networks:
      - mern_network
    environment:
      VITE_API_URL: http://localhost:3000
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    restart: unless-stopped
   
networks:
  mern_network:
    driver: bridge
