name: Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # FRONTEND
      - name: Install Frontend Dependencies
        working-directory: Frontend
        run: npm install

      - name: Build Frontend
        working-directory: Frontend
        run: npm run build

      # BACKEND
      - name: Install Backend Dependencies
        working-directory: Backend
        run: npm install

  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # BACKEND TESTS
      - name: Install Backend Dependencies
        working-directory: tests
        run: npm install

      - name: Run Backend
        working-directory: Backend
        run: nodemon main

      - name: Run Backend Test
        working-directory: tests
        run: npm run test
        env:
         BACKEND_URL: http://localhost:3000

